# Generated by Django 4.0.6 on 2022-08-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_commentscrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_service',
            field=models.CharField(default='-', max_length=200, verbose_name='Услуга'),
        ),
    ]
